[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
[tool.poetry.dependencies]
bcrypt = "*"
python = "^3.7"
termcolor = "*"
pynput = "^1.6"
pysftp = "^0.2.9"
